language: java
sudo: false
jdk:
  - openjdk8
install: true
env:
  matrix:
    - VERSION_JACKSON='-Dversion.jackson=2.6.7' PROJECTS='-pl !fahrschein-typeresolver,!fahrschein-example'
    - VERSION_JACKSON='-Dversion.jackson=2.7.9' PROJECTS='-pl !fahrschein-typeresolver,!fahrschein-example'
    - VERSION_JACKSON='-Dversion.jackson=2.8.11'
    - DEFAULTS=''
script: mvn -V $VERSION_JACKSON $PROJECTS $FAIL_ON_WARN clean verify
addons:
  postgresql: "9.4"